/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Tea {
      
    export type TeaBatchStruct = {batchId: BigNumberish, farmerBatchId: string, origin: string, harvestDate: BigNumberish, packagedDate: BigNumberish, processingMethod: string, certifications: string, currentOwner: AddressLike, state: BigNumberish, farmer: AddressLike, processor: AddressLike, latestExporter: AddressLike, latestDistributor: AddressLike, latestRetailer: AddressLike}

    export type TeaBatchStructOutput = [batchId: bigint, farmerBatchId: string, origin: string, harvestDate: bigint, packagedDate: bigint, processingMethod: string, certifications: string, currentOwner: string, state: bigint, farmer: string, processor: string, latestExporter: string, latestDistributor: string, latestRetailer: string] & {batchId: bigint, farmerBatchId: string, origin: string, harvestDate: bigint, packagedDate: bigint, processingMethod: string, certifications: string, currentOwner: string, state: bigint, farmer: string, processor: string, latestExporter: string, latestDistributor: string, latestRetailer: string }
  
    }

  export interface TeaInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "DISTRIBUTOR_ROLE" | "END_CONSUMER_ROLE" | "EXPORTER_ROLE" | "FARMER_ROLE" | "PROCESSOR_ROLE" | "RETAILER_ROLE" | "acceptTransfer" | "batches" | "consumeBatch" | "distributeBatch" | "exportBatch" | "getBatch" | "getBatchBasic" | "getCurrentBatchId" | "getRoleAdmin" | "grantRole" | "hasRole" | "markRetail" | "pendingTransfers" | "processBatch" | "proposeTransfer" | "registerBatch" | "renounceRole" | "revokeRole" | "supportsInterface" | "withdrawETH"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchConsumed" | "BatchDistributed" | "BatchExported" | "BatchProcessed" | "BatchRegistered" | "BatchRetail" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "TransferCompleted" | "TransferProposed"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DISTRIBUTOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'END_CONSUMER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'EXPORTER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'FARMER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PROCESSOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'RETAILER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptTransfer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'batches', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'consumeBatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'distributeBatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'exportBatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBatchBasic', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCurrentBatchId', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'markRetail', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pendingTransfers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'processBatch', values: [BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'proposeTransfer', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'registerBatch', values: [string, string, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'withdrawETH', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DISTRIBUTOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'END_CONSUMER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'EXPORTER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FARMER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PROCESSOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RETAILER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batches', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'consumeBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exportBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatchBasic', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCurrentBatchId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markRetail', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingTransfers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawETH', data: BytesLike): Result;
  }

  
    export namespace BatchConsumedEvent {
      export type InputTuple = [batchId: BigNumberish];
      export type OutputTuple = [batchId: bigint];
      export interface OutputObject {batchId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchDistributedEvent {
      export type InputTuple = [batchId: BigNumberish];
      export type OutputTuple = [batchId: bigint];
      export interface OutputObject {batchId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchExportedEvent {
      export type InputTuple = [batchId: BigNumberish];
      export type OutputTuple = [batchId: bigint];
      export interface OutputObject {batchId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchProcessedEvent {
      export type InputTuple = [batchId: BigNumberish];
      export type OutputTuple = [batchId: bigint];
      export interface OutputObject {batchId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchRegisteredEvent {
      export type InputTuple = [batchId: BigNumberish, farmerBatchId: string, owner: AddressLike];
      export type OutputTuple = [batchId: bigint, farmerBatchId: string, owner: string];
      export interface OutputObject {batchId: bigint, farmerBatchId: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchRetailEvent {
      export type InputTuple = [batchId: BigNumberish];
      export type OutputTuple = [batchId: bigint];
      export interface OutputObject {batchId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferCompletedEvent {
      export type InputTuple = [batchId: BigNumberish, from: AddressLike, to: AddressLike];
      export type OutputTuple = [batchId: bigint, from: string, to: string];
      export interface OutputObject {batchId: bigint, from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferProposedEvent {
      export type InputTuple = [batchId: BigNumberish, from: AddressLike, to: AddressLike];
      export type OutputTuple = [batchId: bigint, from: string, to: string];
      export interface OutputObject {batchId: bigint, from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Tea extends BaseContract {
    
    connect(runner?: ContractRunner | null): Tea;
    waitForDeployment(): Promise<this>;

    interface: TeaInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DISTRIBUTOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    END_CONSUMER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    EXPORTER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    FARMER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PROCESSOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    RETAILER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    acceptTransfer: TypedContractMethod<
      [batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    batches: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, string, string, string, bigint, string, string, string, string, string] & {batchId: bigint, farmerBatchId: string, origin: string, harvestDate: bigint, packagedDate: bigint, processingMethod: string, certifications: string, currentOwner: string, state: bigint, farmer: string, processor: string, latestExporter: string, latestDistributor: string, latestRetailer: string }],
      'view'
    >
    

    
    consumeBatch: TypedContractMethod<
      [batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    distributeBatch: TypedContractMethod<
      [batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    exportBatch: TypedContractMethod<
      [batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getBatch: TypedContractMethod<
      [batchId: BigNumberish, ],
      [Tea.TeaBatchStructOutput],
      'view'
    >
    

    
    getBatchBasic: TypedContractMethod<
      [batchId: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, string, bigint]],
      'view'
    >
    

    
    getCurrentBatchId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    markRetail: TypedContractMethod<
      [batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    pendingTransfers: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, boolean] & {from: string, to: string, exists: boolean }],
      'view'
    >
    

    
    processBatch: TypedContractMethod<
      [batchId: BigNumberish, packagedDate: BigNumberish, processingMethod: string, ],
      [void],
      'nonpayable'
    >
    

    
    proposeTransfer: TypedContractMethod<
      [batchId: BigNumberish, to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registerBatch: TypedContractMethod<
      [farmerBatchId: string, origin: string, harvestDate: BigNumberish, certifications: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    withdrawETH: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DISTRIBUTOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'END_CONSUMER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'EXPORTER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'FARMER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PROCESSOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'RETAILER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'acceptTransfer'): TypedContractMethod<
      [batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'batches'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, string, string, string, bigint, string, string, string, string, string] & {batchId: bigint, farmerBatchId: string, origin: string, harvestDate: bigint, packagedDate: bigint, processingMethod: string, certifications: string, currentOwner: string, state: bigint, farmer: string, processor: string, latestExporter: string, latestDistributor: string, latestRetailer: string }],
      'view'
    >;
getFunction(nameOrSignature: 'consumeBatch'): TypedContractMethod<
      [batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'distributeBatch'): TypedContractMethod<
      [batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'exportBatch'): TypedContractMethod<
      [batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBatch'): TypedContractMethod<
      [batchId: BigNumberish, ],
      [Tea.TeaBatchStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getBatchBasic'): TypedContractMethod<
      [batchId: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, string, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getCurrentBatchId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'markRetail'): TypedContractMethod<
      [batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pendingTransfers'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, boolean] & {from: string, to: string, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'processBatch'): TypedContractMethod<
      [batchId: BigNumberish, packagedDate: BigNumberish, processingMethod: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proposeTransfer'): TypedContractMethod<
      [batchId: BigNumberish, to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerBatch'): TypedContractMethod<
      [farmerBatchId: string, origin: string, harvestDate: BigNumberish, certifications: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawETH'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BatchConsumed'): TypedContractEvent<BatchConsumedEvent.InputTuple, BatchConsumedEvent.OutputTuple, BatchConsumedEvent.OutputObject>;
getEvent(key: 'BatchDistributed'): TypedContractEvent<BatchDistributedEvent.InputTuple, BatchDistributedEvent.OutputTuple, BatchDistributedEvent.OutputObject>;
getEvent(key: 'BatchExported'): TypedContractEvent<BatchExportedEvent.InputTuple, BatchExportedEvent.OutputTuple, BatchExportedEvent.OutputObject>;
getEvent(key: 'BatchProcessed'): TypedContractEvent<BatchProcessedEvent.InputTuple, BatchProcessedEvent.OutputTuple, BatchProcessedEvent.OutputObject>;
getEvent(key: 'BatchRegistered'): TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
getEvent(key: 'BatchRetail'): TypedContractEvent<BatchRetailEvent.InputTuple, BatchRetailEvent.OutputTuple, BatchRetailEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'TransferCompleted'): TypedContractEvent<TransferCompletedEvent.InputTuple, TransferCompletedEvent.OutputTuple, TransferCompletedEvent.OutputObject>;
getEvent(key: 'TransferProposed'): TypedContractEvent<TransferProposedEvent.InputTuple, TransferProposedEvent.OutputTuple, TransferProposedEvent.OutputObject>;

    filters: {
      
      'BatchConsumed(uint256)': TypedContractEvent<BatchConsumedEvent.InputTuple, BatchConsumedEvent.OutputTuple, BatchConsumedEvent.OutputObject>;
      BatchConsumed: TypedContractEvent<BatchConsumedEvent.InputTuple, BatchConsumedEvent.OutputTuple, BatchConsumedEvent.OutputObject>;
    

      'BatchDistributed(uint256)': TypedContractEvent<BatchDistributedEvent.InputTuple, BatchDistributedEvent.OutputTuple, BatchDistributedEvent.OutputObject>;
      BatchDistributed: TypedContractEvent<BatchDistributedEvent.InputTuple, BatchDistributedEvent.OutputTuple, BatchDistributedEvent.OutputObject>;
    

      'BatchExported(uint256)': TypedContractEvent<BatchExportedEvent.InputTuple, BatchExportedEvent.OutputTuple, BatchExportedEvent.OutputObject>;
      BatchExported: TypedContractEvent<BatchExportedEvent.InputTuple, BatchExportedEvent.OutputTuple, BatchExportedEvent.OutputObject>;
    

      'BatchProcessed(uint256)': TypedContractEvent<BatchProcessedEvent.InputTuple, BatchProcessedEvent.OutputTuple, BatchProcessedEvent.OutputObject>;
      BatchProcessed: TypedContractEvent<BatchProcessedEvent.InputTuple, BatchProcessedEvent.OutputTuple, BatchProcessedEvent.OutputObject>;
    

      'BatchRegistered(uint256,string,address)': TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
      BatchRegistered: TypedContractEvent<BatchRegisteredEvent.InputTuple, BatchRegisteredEvent.OutputTuple, BatchRegisteredEvent.OutputObject>;
    

      'BatchRetail(uint256)': TypedContractEvent<BatchRetailEvent.InputTuple, BatchRetailEvent.OutputTuple, BatchRetailEvent.OutputObject>;
      BatchRetail: TypedContractEvent<BatchRetailEvent.InputTuple, BatchRetailEvent.OutputTuple, BatchRetailEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'TransferCompleted(uint256,address,address)': TypedContractEvent<TransferCompletedEvent.InputTuple, TransferCompletedEvent.OutputTuple, TransferCompletedEvent.OutputObject>;
      TransferCompleted: TypedContractEvent<TransferCompletedEvent.InputTuple, TransferCompletedEvent.OutputTuple, TransferCompletedEvent.OutputObject>;
    

      'TransferProposed(uint256,address,address)': TypedContractEvent<TransferProposedEvent.InputTuple, TransferProposedEvent.OutputTuple, TransferProposedEvent.OutputObject>;
      TransferProposed: TypedContractEvent<TransferProposedEvent.InputTuple, TransferProposedEvent.OutputTuple, TransferProposedEvent.OutputObject>;
    
    };
  }